# Generated by Django 4.2.20 on 2025-05-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_first_name',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_last_name',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_org_id',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_org_name',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_user_id',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_till',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
